# Generated by Django 3.0.5 on 2020-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20200513_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
