# Generated by Django 3.0.5 on 2020-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_auto_20200513_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworks',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
