# Generated by Django 3.0.5 on 2020-05-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0006_auto_20200514_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworks',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 14, 20, 49, 33, 352171)),
        ),
    ]
